spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuebiChain?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: yyjyroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations: classpath:/static/,file:${user.dir}/uploads/

server:
  port: 8081

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: test
    access-key-secret: test
    bucket-name: your-bucket
    file-host: avatar

fabric:
  cli:
    path: /Users/hypoxic/fabric-samples/test-network
    bin: /Users/hypoxic/fabric-samples/bin

mybatis:
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-dir: uploads/avatars
